# Generated by Django 4.2.5 on 2023-10-21 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('matn', models.TextField()),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('yuklangan_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yangilash_vaqti', models.DateTimeField(auto_now=True)),
                ('rasm', models.ImageField(upload_to='news/rasm')),
                ('status', models.CharField(choices=[('S', 'Successfully'), ('F', 'Fail')], default='F', max_length=1)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.kategoriya')),
            ],
        ),
    ]
